.PHONY: help install dev dev-api dev-app lint-js test-js build-dapp deploy-worker deploy-secrets pages-init deploy-pages smoke build test lint bindings deploy upgrade invoke
.DEFAULT_GOAL := help
SHELL:=/bin/bash

# staging = testnet, production = mainnet
ifndef network
   override network = testnet
endif

ifndef admin
   override admin = stellar-members-$(network)
endif

ifndef attester
   override attester = stellar-members-attester-$(network)
endif

ifndef wasm
	override wasm = target/wasm32v1-none/release/stellar_membership.wasm
endif

override deployment = contracts/deployments/stellar-membership-$(network)

override contract_id = $(shell cat $(deployment))

# Neural Quorum Governance, read by `governance` and fixed at deployment
ifeq ($(network),testnet)
   override nqg_contract = CAM3VZX47TCQWCEYGXEDTSIJYKIVM6AWMFR7VTFYTETXFO53I5LOZGBT
endif

# The generator imports types as values, which bundlers refuse, and emits
# code that strict tsc rejects. Three substitutions on the generated file.
override nocheck = s/\A/\/\/ \@ts-nocheck generated by `make bindings`, do not edit\n/
override drop_type_values = s/^  (ClientOptions as ContractClientOptions|MethodOptions|Result),\n//mg
override type_import = import type {\n  ClientOptions as ContractClientOptions,\n  MethodOptions,\n  Result,\n} from "\@stellar\/stellar-sdk\/contract";
override add_type_import = s/^\} from "\@stellar\/stellar-sdk\/contract";\n/} from "\@stellar\/stellar-sdk\/contract";\n$(type_import)\n/m

# Add help text after each target name starting with '\#\#'
help:   ## show this help
	@echo -e "Help for this makefile\n"
	@echo "Possible commands are:"
	@grep -h "##" $(MAKEFILE_LIST) | grep -v grep | sed -e 's/\(.*\):.*##\(.*\)/    \1: \2/'

# --------- Dapp and worker --------- #

install:  ## install the dapp and the worker
	cd dapp && bun install
	cd worker && bun install

dev:  ## the worker on 8787 and the app on http://localhost:5173, Ctrl-C stops both
	cd worker && bun run dev & cd dapp && bun run dev

dev-api:  ## only the worker, under Bun on 8787
	cd worker && bun run dev

dev-app:  ## only the app, with /api proxied to the worker
	cd dapp && bun run dev

lint-js:  ## prettier, eslint and tsc of the dapp and the worker
	cd dapp && bun run lint
	cd worker && bun run lint

test-js:  ## tests of the dapp, of the shared code with it, and of the worker
	cd dapp && bun run test
	cd worker && bun run test

build-dapp:  ## static build in dapp/dist: VITE_API_URL the worker's origin, VITE_NETWORK the network, BASE_PATH the path it is served under
	cd dapp && bun run build

deploy-worker:  ## deploy the worker with wrangler
	cd worker && bun run deploy

deploy-secrets:  ## push every secret of worker/.dev.vars to Cloudflare at once
	cd worker && bun run deploy:secrets

smoke:  ## end-to-end flows on testnet through the worker
	cd worker && bun run smoke

# --------- Radicle Pages --------- #

# The site is the whole content of the `pages` branch, which Radicle Pages
# serves. That branch is checked out once as an orphan worktree in `pages/`,
# so a deployment is a build copied there, committed and pushed.
override pages_dir = pages
override worker_url = https://stellar-members.tansu-964.workers.dev

# Radicle Pages serves the repository under its alias, so the build is for
# that path. The day the app has a domain of its own: `make deploy-pages base=/`.
ifndef base
   override base = /stellar-members/
endif

pages-init:  ## one-time: the canonical pages branch and the worktree that builds into it
	rad id update \
		--title "Configure the pages canonical branch" \
		--description "Radicle Pages serves the site from refs/heads/pages" \
		--payload xyz.radicle.crefs rules \
		'{"refs/heads/pages": {"allow": "delegates", "threshold": 1}}'
	rad sync
	git worktree add --orphan -b $(pages_dir) $(pages_dir)

deploy-pages:  ## build the app and publish it to Radicle Pages
	@test -e $(pages_dir)/.git || { echo "run 'make pages-init' first"; exit 1; }
	@test -z "$$(git status --porcelain)" \
		|| { echo "commit first: a publish names the commit it was built from"; exit 1; }
	VITE_API_URL=$(worker_url) VITE_NETWORK=$(network) BASE_PATH=$(base) $(MAKE) build-dapp
	find $(pages_dir) -mindepth 1 -maxdepth 1 ! -name .git -exec rm -rf {} +
	cp -R dapp/dist/. $(pages_dir)/
	git -C $(pages_dir) add -A
	git -C $(pages_dir) commit -q -m "Publish $(shell git rev-parse --short HEAD)" \
		|| echo "the build is identical, publishing it again"
	git -C $(pages_dir) push rad $(pages_dir)

# --------- Contract build/test/deploy --------- #

build:  ## build the contract WASM
	stellar contract build --optimize
	@ls -l target/wasm32v1-none/release/*.wasm

test:  ## contract tests
	cargo test

lint:  ## clippy and rustfmt
	cargo clippy --all-targets --all-features -- -Dwarnings
	cargo fmt --check

bindings: build  ## regenerate the contract bindings of the dapp and the worker
	stellar contract bindings typescript --wasm $(wasm) --output-dir target/bindings --overwrite
	perl -0777 -pe '$(nocheck); $(drop_type_values); $(add_type_import)' \
		target/bindings/src/index.ts > dapp/src/bindings/index.ts
	cp dapp/src/bindings/index.ts worker/src/bindings/index.ts

deploy: build  ## deploy the contract with the admin and attester identities
	id=$$(stellar contract deploy \
		--wasm $(wasm) \
		--source-account $(admin) \
		--network $(network) \
		--salt $(shell printf stellar-membership | openssl sha256 | cut -d " " -f2) \
		-- \
		--admin $(shell stellar keys address $(admin)) \
		--attester $(shell stellar keys address $(attester)) \
		--name "Stellar Members" --symbol SMBR \
		--uri https://ipfs.io/ipfs/QmVTqJ4EzJThVWobgyaWCetcrXCjftQhgi24E4giJ5EgXr \
		--uri_trait https://ipfs.io/ipfs/Qmddf2UgGTQ3z2SZfg2ziZJzDJDRS3Dk7Z3phZ76fMzdLf \
		--nqg_contract $(nqg_contract)) && \
	echo "$$id" > $(deployment) && \
	cat $(deployment)

upgrade: build  ## upgrade the deployed contract in place
	stellar contract invoke \
		--source-account $(admin) \
		--network $(network) \
		--id $(contract_id) \
		-- \
		upgrade \
		--wasm_hash $(shell stellar contract upload --source-account $(admin) --network $(network) --wasm $(wasm))

invoke:  ## call a function as the admin: make invoke fn=member args="--token_id 0"
	stellar contract invoke \
		--source-account $(admin) \
		--network $(network) \
		--id $(contract_id) \
		-- \
		$(fn) $(args)
