.PHONY: help install dev dev-api dev-app lint-js test-js build-dapp deploy-worker smoke build test lint bindings deploy upgrade invoke
.DEFAULT_GOAL := help
SHELL:=/bin/bash

# staging = testnet, production = mainnet
ifndef network
   override network = testnet
endif

ifndef admin
   override admin = stellar-members-$(network)
endif

ifndef attester
   override attester = stellar-members-attester-$(network)
endif

ifndef wasm
	override wasm = target/wasm32v1-none/release/stellar_membership.wasm
endif

override deployment = contracts/deployments/stellar-membership-$(network)

override contract_id = $(shell cat $(deployment))

# Neural Quorum Governance, read by `governance` and fixed at deployment
ifeq ($(network),testnet)
   override nqg_contract = CAM3VZX47TCQWCEYGXEDTSIJYKIVM6AWMFR7VTFYTETXFO53I5LOZGBT
endif

# The generator imports types as values, which bundlers refuse, and emits
# code that strict tsc rejects. Three substitutions on the generated file.
override nocheck = s/\A/\/\/ \@ts-nocheck generated by `make bindings`, do not edit\n/
override drop_type_values = s/^  (ClientOptions as ContractClientOptions|MethodOptions|Result),\n//mg
override type_import = import type {\n  ClientOptions as ContractClientOptions,\n  MethodOptions,\n  Result,\n} from "\@stellar\/stellar-sdk\/contract";
override add_type_import = s/^\} from "\@stellar\/stellar-sdk\/contract";\n/} from "\@stellar\/stellar-sdk\/contract";\n$(type_import)\n/m

# Add help text after each target name starting with '\#\#'
help:   ## show this help
	@echo -e "Help for this makefile\n"
	@echo "Possible commands are:"
	@grep -h "##" $(MAKEFILE_LIST) | grep -v grep | sed -e 's/\(.*\):.*##\(.*\)/    \1: \2/'

# --------- Dapp and worker --------- #

install:  ## install the dapp and the worker
	cd dapp && bun install
	cd worker && bun install

dev:  ## the worker on 8787 and the app on http://localhost:5173, Ctrl-C stops both
	cd worker && bun run dev & cd dapp && bun run dev

dev-api:  ## only the worker, under Bun on 8787
	cd worker && bun run dev

dev-app:  ## only the app, with /api proxied to the worker
	cd dapp && bun run dev

lint-js:  ## prettier, eslint and tsc of the dapp and the worker
	cd dapp && bun run lint
	cd worker && bun run lint

test-js:  ## tests of the dapp, of the shared code with it, and of the worker
	cd dapp && bun run test
	cd worker && bun run test

build-dapp:  ## static build in dapp/dist, VITE_API_URL is the worker's origin
	cd dapp && bun run build

deploy-worker:  ## deploy the worker with wrangler
	cd worker && bun run deploy

smoke:  ## end-to-end flows on testnet through the worker
	cd worker && bun run smoke

# --------- Contract build/test/deploy --------- #

build:  ## build the contract WASM
	stellar contract build --optimize
	@ls -l target/wasm32v1-none/release/*.wasm

test:  ## contract tests
	cargo test

lint:  ## clippy and rustfmt
	cargo clippy --all-targets --all-features -- -Dwarnings
	cargo fmt --check

bindings: build  ## regenerate the contract bindings of the dapp and the worker
	stellar contract bindings typescript --wasm $(wasm) --output-dir target/bindings --overwrite
	perl -0777 -pe '$(nocheck); $(drop_type_values); $(add_type_import)' \
		target/bindings/src/index.ts > dapp/src/bindings/index.ts
	cp dapp/src/bindings/index.ts worker/src/bindings/index.ts

deploy: build  ## deploy the contract with the admin and attester identities
	stellar contract deploy \
		--wasm $(wasm) \
		--source-account $(admin) \
		--network $(network) \
		--salt $(shell printf stellar-membership | openssl sha256 | cut -d " " -f2) \
		-- \
		--admin $(shell stellar keys address $(admin)) \
		--attester $(shell stellar keys address $(attester)) \
		--name "Stellar Members" --symbol SMBR \
		--uri https://ipfs.io/ipfs/QmVTqJ4EzJThVWobgyaWCetcrXCjftQhgi24E4giJ5EgXr \
		--uri_trait https://ipfs.io/ipfs/Qmddf2UgGTQ3z2SZfg2ziZJzDJDRS3Dk7Z3phZ76fMzdLf \
		--nqg_contract $(nqg_contract) \
		> $(deployment) && \
	cat $(deployment)

upgrade: build  ## upgrade the deployed contract in place
	stellar contract invoke \
		--source-account $(admin) \
		--network $(network) \
		--id $(contract_id) \
		-- \
		upgrade \
		--wasm_hash $(shell stellar contract upload --source-account $(admin) --network $(network) --wasm $(wasm))

invoke:  ## call a function as the admin: make invoke fn=member args="--token_id 0"
	stellar contract invoke \
		--source-account $(admin) \
		--network $(network) \
		--id $(contract_id) \
		-- \
		$(fn) $(args)
