.DEFAULT_GOAL := help
SHELL := /bin/bash

# staging = testnet, production = mainnet
network ?= testnet
admin ?= stellar-members-$(network)
attester ?= stellar-members-attester-$(network)
wasm = target/wasm32v1-none/release/stellar_membership.wasm
deployment = contracts/deployments/stellar-membership-$(network)
contract_id = $(shell cat $(deployment))
# Neural Quorum Governance, given to the contract at deployment and never
# settable afterwards: one per network, and no default.
nqg_contract_testnet = CAM3VZX47TCQWCEYGXEDTSIJYKIVM6AWMFR7VTFYTETXFO53I5LOZGBT
nqg_contract = $(nqg_contract_$(network))

help:  ## list the targets
	@grep -E '^[a-z_-]+:.*##' $(MAKEFILE_LIST) | awk -F ':.*## ' '{printf "  %-24s %s\n", $$1, $$2}'

# --------- dapp and worker --------- #

install:  ## install the dapp and the worker
	cd dapp && bun install
	cd worker && bun install

dev:  ## the worker under Bun on 8787 and the app on http://localhost:5173
	trap 'kill 0' EXIT; (cd worker && bun run dev) & (cd dapp && bun run dev) & wait -n

lint-js:  ## prettier, eslint and tsc of the dapp and the worker
	cd dapp && bun run lint
	cd worker && bun run lint

test-js:  ## tests of the dapp, of the shared code with it, and of the worker
	cd dapp && bun run test
	cd worker && bun run test

build-dapp:  ## static build in dapp/dist, VITE_API_URL is the worker's origin
	cd dapp && bun run build

deploy-worker:  ## deploy the worker with wrangler
	cd worker && bun run deploy

smoke:  ## end-to-end flows on testnet through the worker
	cd worker && bun run smoke

# --------- contract --------- #

build:  ## build the contract WASM
	stellar contract build --optimize

test:  ## contract tests
	cargo test

lint:  ## clippy and rustfmt
	cargo clippy --all-targets --all-features -- -Dwarnings && cargo fmt --check

bindings: build  ## regenerate the TypeScript bindings of the dapp and the worker
	stellar contract bindings typescript --wasm $(wasm) --output-dir target/bindings --overwrite
	for dir in dapp worker; do \
	  { printf '// @ts-nocheck generated by `make bindings`, do not edit\n'; \
	    perl -0pe '$(type_imports)' target/bindings/src/index.ts; } > $$dir/src/bindings/index.ts; \
	done

# the generator imports types as values, which bundlers refuse
type_imports = s/import \{\s*AssembledTransaction,\s*Client as ContractClient,\s*ClientOptions as ContractClientOptions,\s*MethodOptions,\s*Result,\s*Spec as ContractSpec,?\s*\} from "\@stellar\/stellar-sdk\/contract";/import {\n  AssembledTransaction,\n  Client as ContractClient,\n  Spec as ContractSpec,\n} from "\@stellar\/stellar-sdk\/contract";\nimport type {\n  ClientOptions as ContractClientOptions,\n  MethodOptions,\n  Result,\n} from "\@stellar\/stellar-sdk\/contract";/

deploy: build  ## deploy the contract with the admin and attester identities
	@test -n "$(nqg_contract)" || \
		{ echo "set nqg_contract_$(network) in the Makefile first"; exit 1; }
	id=$$(stellar contract deploy \
		--wasm $(wasm) \
		--source-account $(admin) \
		--network $(network) \
		--salt $(shell printf stellar-membership | openssl sha256 | cut -d " " -f2) \
		-- \
		--admin $(shell stellar keys address $(admin)) \
		--attester $(shell stellar keys address $(attester)) \
		--name "Stellar Members" --symbol SMBR \
		--uri https://ipfs.io/ipfs/QmVTqJ4EzJThVWobgyaWCetcrXCjftQhgi24E4giJ5EgXr \
		--uri_trait https://ipfs.io/ipfs/Qmddf2UgGTQ3z2SZfg2ziZJzDJDRS3Dk7Z3phZ76fMzdLf \
		--nqg_contract $(nqg_contract)) && \
	echo "$$id" | tee $(deployment)

upgrade: build  ## upgrade the deployed contract in place
	stellar contract invoke \
		--source-account $(admin) \
		--network $(network) \
		--id $(contract_id) \
		-- \
		upgrade \
		--wasm_hash $(shell stellar contract upload --source-account $(admin) --network $(network) --wasm $(wasm))

invoke:  ## call a function as the admin: make invoke fn=member args="--token_id 0"
	stellar contract invoke \
		--source-account $(admin) \
		--network $(network) \
		--id $(contract_id) \
		-- \
		$(fn) $(args)

.PHONY: help install dev lint-js test-js build-dapp deploy-worker smoke build test lint bindings deploy upgrade invoke
